sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Jix6H/h+da9QUsdAil6h+LM0ShsF2ofPFXUsTVKzATkNJvjGzo+ZoAnmRlN4TiqseC+sAoYmbnk6o/5jWqsXiq1XXDQcyS9FhNRkUbWkKxPiPwgk/k7Ru1MB8CGGkxKrHqXd7bJL565Dtsleo4GEmx+/zubIj298QlDJejlhaHjA7DkDcNhnVq60/rZc/U/Nze3c0zttuBl7LFHKGHsbtfFIK3uNM97DneI3ky/DkU5jr2HoYwJdxYJW3X+bh+4LL3DDI/9OyiHmZ1bU29AWrWXvjQU8iKFhaLp1bSGBTnqeNH8dLt7VIQ+TWDe1h7HDXm2LzvKFncGlDmZTeEe/MntkVOHXxiqnRibBuiQYKVHQE2U5/9bhmDPKCnYQQ6zdaw3b4whWSCix4fAyCUqIQWTocUWwS30kaWGeYF+QSndTYkeoCn38alx8j+bftOrx1h2qNdxWZPKMhq405vpxWR5RtXwMhEtBzivRBDZrXQLIsMpczqfDW7DE5N7a+QMfqUKeLrs9L3dCH53aUZouwV/yJqufHkhNAOPcKdRgn4X6k6tQK+tQzmdwU/ddvmnxBlkBWPkhmUEYS3v2QBJIl7PwzHi3nwTjh1OEmq2pCj4/s7EAWwrJZC395k6I7iPeMKvhh7RmMwJAEFkqqRPryewm8qIcI0p0jHmrXqh5B5M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Little-Men_2788
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy